CREATE TABLE IF NOT EXISTS vouchers (
  id UUID PRIMARY KEY,
  code VARCHAR(20) UNIQUE NOT NULL,
  owner_email VARCHAR(255),
  balance_cents INTEGER DEFAULT 0,
  currency VARCHAR(10) DEFAULT 'ZAR',
  status VARCHAR(20) DEFAULT 'active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
